# Generated by Django 5.1.3 on 2024-12-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='capno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='cno',
            field=models.IntegerField(),
        ),
    ]
